name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT  }} | docker login ghcr.io -u Dhruvil-98 --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/dhruvil-98/todo-app/my-flask-app:latest .
        docker push ghcr.io/dhruvil-98/todo-app/my-flask-app:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Set up kubectl context
      run: |
        kubectl config set-cluster my-cluster --server=https://your-k8s-api-server
        kubectl config set-credentials my-credentials --token=${{ secrets.KUBECONFIG }}
        kubectl config set-context my-context --cluster=my-cluster --user=my-credentials
        kubectl config use-context my-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        kubectl apply -f kubernetes/configmap.yaml